### ISSUE TITLE
Recherche für Integration von Instagram in die Website

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#24]
## ToDo

- [x] Spike für Themenrecherche durchführen

**Comment by DanielMerkl** [comment]
# Ergebnis

Die Einbindung des Instagram-Feeds ist technisch möglich.

## Dokumentation
https://developers.facebook.com/docs/instagram-basic-display-api/

## Voraussetzungen
- [ ] Meta-Developer Account (hier bietet es sich vermutlich an, den bereits existierenden Meta Account des RGC als Basis zu verwenden)
- [ ] Zugriff auf den Instagram Account des RGC

## Anmerkungen
Die Instagram API ist dahingehend limitiert, dass maximal 200 Anfragen pro Stunde gemacht werden können. Demzufolge kann das Laden der aktuellsten Instagram Posts nicht Client-seitig stattfinden, sondern muss vorab per Static-Site-Generation durchgeführt werden. Instagram-Posts würden also erst dann auf der RGC Webseite erscheinen, nachdem diese neu generiert wurde.
