### ISSUE TITLE
Header (bzw. Navigation) entwickeln

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#26]
Video für Inspiration bzw. besseres Verständnis
https://www.youtube.com/watch?v=r8m2wM7eXeU&ab_channel=TheWebsiteArchitect

# Wichtige Bestandteile

- [x] Verlinkungen zu den wichtigsten Seiten
- [x] ein links angeordnetes Logo zur Identifizierung der Webseite
- [ ] CTA (z.B. "zum Angebot" / "Schnuppertraining vereinbaren" (optional)

# Aufbau der Navigationslinks

- [x] News
- [x] Angebot
  - [ ] Turniertanz Standard
  - [ ] Turniertanz Latein
  - [ ] Kindertanzen
  - [ ] Kinder / Junioren / Jugend Standard
  - [ ] Kinder / Junioren / Jugend Latein
  - [ ] Standardformation
  - [ ] Lateinformation
  - [ ] Freizeittanz
- [x] Events
- [x] Turnierergebnisse
- [x] Der Verein (? eventuell besser: "Der RGC")
- [x] Kontakt (? eventuell könnte man den Punkt in den Footer verlagern...)

# Akzeptanzkriterien

- [x] Der Header ist [sticky](https://developer.mozilla.org/en-US/docs/Web/CSS/position?retiredLocale=de)
- [x] Im linken Bereich des Headers ist das RGC logo sichtbar
- [x] Beim Klicken auf das Logo wird man auf die Startseite verlinkt
- [x] Beim Scrollen nach unten wird der Header ausgeblendet
- [x] Sobald die Scrollrichtung nach oben wechselt, wird der Header wieder eingeblendet (siehe [Videobeispiel](https://youtu.be/r8m2wM7eXeU?t=330) und [mögliche Implementierung](https://www.codemzy.com/blog/react-sticky-header-disappear-scroll))
- [x] Der Header ist responsive, d.h. ab einer bestimmten Größe müssen die vertikal angeordneten Navigationslinks in ein Hamburger-Menü angezeigt werden
- [x] Alle Navigationslinks und Menüpunkte in Dropdown-Menüs sind Keyboard Accessible
- [x] Es ist erkennbar, auf welcher Seite man sich aktuell befindet (z.B. durch Unterstreichen des Navigationslinks)
- [ ] Dropdown-Menüs sind durch einen Indikator (z.B. kleiner Pfeil) erkennbar, der je nach Zustand des Dropdowns (offen / geschlossen) seine Richtung (oben / unten) ändert (siehe "chevron-down" & "chevron-up" bei [Heroicons](https://heroicons.com/))
- [ ] Die einzelnen Seiten werden beim Hovern des jeweiligen Navigationslinks schon vor dem Klick vorgeladen (vgl. [pre-loading von NextLink](https://nextjs.org/docs/api-reference/next/link))
# TODOs

- [ ] Diskussion: Sollte das Tanzangebot in der Navi über ein Dropdown aufgeklappt werden können oder sollte es eine spezielle Page dafür geben?
- [ ] festlegen, welche Seiten eine höhere Priorität haben (niedriger priorisierte Unterseiten sollten in Dropdown-Menüs ausgelagert werden)
- [ ] Aufbau bzw. Struktur der Navigationslinks / Dropdown-Menüs finalisieren
- [x] Wireframe für grobe Struktur erstellen
- [ ] [Headless UI Menu](https://headlessui.com/react/menu) in Kombination mit [Daisy UI Dropdown](https://daisyui.com/components/dropdown/) implementieren
- [x] Diskutieren und festlegen, ob der Punkt "Kontakt" (inkl. des Unterpunktes "Showanfragen") in den Footer verlagert werden sollte
