### ISSUE TITLE
Footer entwickeln

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#27]
[Video für besseres Verständnis](https://www.youtube.com/watch?v=T5BACF2goFU&t=6s&ab_channel=TheWebsiteArchitect)

# Zentrale Use-Cases für den Footer

- Inhalte auflisten, die sich nicht in der Hauptnavigation (Header) befinden (z.B. Kontakt, Impressum, Datenschutz etc.)
- zweite Chance, potenzielle neue Mitglieder von dem Verein zu überzeugen

# Möglicher Aufbau: 4-Spalten-Layout

## (1. Spalte) Zusammenfassung der wichtigsten Punkte zum Verein

- [x] Logo
- [x] Name des Vereins
- [x] kurzer Paragraph zum Verein (könnte beispielsweise beinhalten: Gründungsjahr, Anzahl Mitglieder, Erwähnung von speziellen Erfolgen, etc.)

## (2. Spalte) Alle Links der Hauptnavigation + weitere Unterseiten, die nicht in der Hauptnavigation aufgelistet werden

Das Prinzip der nochmaligen Auflistung aller Navigationsmöglichkeiten im Footer ist auch bekannt unter dem Begriff "Doormat Navigation".

- [x] Home
- [x] News
- [x] Veranstaltungen
- [x] etc. (TODO: konkretisieren)
- [x] Impressum (#4)
- [x] Datenschutzerklärung (#3)

## (3. Spalte) Sektion mit allen Services bzw. Angeboten

- [x] Turniertanz Standard
- [x] Freizeittanz
- [x] etc. (TODO: konkretisieren)

## (4. Spalte) Kontaktinformationen

- [x] Adresse (eventuell mit direkter Verlinkung zu Google Maps)
- [x] E-Mail (TODO: welche E-Mail-Adresse soll für verwendet werden für Anfragen jeder Art?)
- [x] Telefonnummer
- [x] Social Media Links
  - [x] Instagram
  - [x] Facebook

---

# Akzeptanzkriterien

- [x] Der Footer ist auf jeder Seite sichtbar
- [x] Der Footer ist responsive
- [x] Datenschutzerklärung und Impressum sind als Links hinterlegt und verlinken auf die entsprechenden Seiten

# TODOs

- [x] klären, welche Sponsoren aufgelistet werden müssen und in welcher Form dies zu erfolgen hat
- [x] klären, welche Inhalte des Footers über das CMS von den Content-Administratoren anpassbar sein sollen

**Comment by DanielMerkl** [comment]
> @DanielMerkl Folgende Fragen sind noch offen:
> 
> * Was ist mit "kurzer Paragraph zum Verein" in der ersten Spalte gemeint?
> * Ist die dritte Spalte als Formular gedacht oder als Aufzählung der Angebote mit entsprechender Verlinkung?
> * Sollte in der dritten Spalte ein CTA Button vorhanden sein?

Beschreibung entsprechend angepasst
