### ISSUE TITLE
Kontaktformular für Tanzinteressierte

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#28]
# Kontaktformular für Tanzinteressierte

**Als** Tanzinteressierte/r
**möchte ich** mit dem Verein in Kontakt treten können
**um** individuelle Rückfragen zu den Tanzangeboten stellen zu können. 

## Akzeptanzkriterien

- [x] die Seite mit dem Kontaktformular ist leicht zu erreichen über den:
  - [x] Header
  - [x] Footer
- [x] das Formular beinhaltet folgende Felder:
  - [x] Name
  - [x] E-Mail
  - [x] Nachricht
  - [x] Checkbox für Bestätigung der Datenschutzerklärung
- [x] das Formular kann nicht abgeschickt werden, wenn eines der Formular-Felder nicht ausgefüllt ist oder die Checkbox für die Datenschutzerklärung nicht angekreuzt wurde
- [x] nach dem Abschicken des Formulars wird der Nutzer visuell über das erfolgreiche Abschicken informiert (z.B. über eine kleine Snackbar oder einen Success-Alert)
- [x] nach dem Erhalt der Nachricht wird eine Bestätigung an die angegebene E-Mail des Tanzinteressierten geschickt
- [x] bei einem Fehler (z.B. Weiterleitung der Mail über Strapi) wird der Nutzer visuell (beispielsweise über einen Alert) informiert
- [x] alle Nutzereingaben (Name, E-Mail, Nachricht) werden validiert und sanitized, sodass keine Angriffe möglich sind

## TODOs

- [x] klären, an welchen Verteiler die allgemeine Kontaktanfrage verschickt werden soll
- [x] ermitteln, wie E-Mail Versand aktuell funktioniert und ob wir einen alternativen Ansatz benötigen
- [x] Konkreten Inhalt der Bestätigungsmail definieren
- [x] recherchieren, ob die Checkbox gemäß DSGVO überhaupt verpflichtend ist
- [x] statische Assets des Email-Templates auf dem Server hinterlegen

**Comment by DanielMerkl** [comment]
ASP für Datenschutz Tim
