### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#3]
Link zur aktuellen Datenschutzerklärung: http://www.rgc-nuernberg.de/datenschutz/index.php

Allgemeine Informationen zum Thema Datenschutzerklärung: https://www.wbs.legal/it-und-internet-recht/datenschutzrecht/datenschutzerklaerung/

Generator für Datenschutzerklärungen: https://www.wbs.legal/it-und-internet-recht/datenschutzrecht/datenschutzerklaerung/datenschutzgenerator/

# Akzeptanzkriterien

- [x] Die Datenschutzerklärung kann von Content-Administratoren über das CMS angepasst werden
- [x] Die Datenschutzerklärung ist von jeder Seite aus aufrufbar (z.B. über den Footer)

# Zu klären

- [x] Haben wir einen Datenschutzbeauftragten? (Falls ja, sollte dieser angegeben werden)

# TODOs

- [x] Hosting Platform in Datenschutzerklärung aufnehmen

**Comment by DanielMerkl** [comment]
Wir haben keinen offiziellen Datenschutzbeauftragten im Verein, daher muss keine explizite Eintragung erfolgen.

**Comment by DanielMerkl** [comment]
Absatz zur Hosting-Platform in Datenschutzerklärung aufgenommen
