### ISSUE TITLE
Vereinsgeschichte

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#33]
# Vereinsgeschichte

**Als** Besucher der Webseite
**möchte ich** einen Überblick über die Vereinsgeschichte bekommen.

## Akzeptanzkriterien

- [ ] die Ereignisse werden chronologisch angezeigt (Neuestes ganz oben)
- [ ] jedes Ereignis hat folgende Eigenschaften
  - [ ] Datum
  - [ ] Titel
  - [ ] Beschreibung (optional)

## TODOs

- [ ] auf mögliches Design festlegen (Inspirationen: [A](https://codemyui.com/tag/timeline/), [B](https://flowbite.com/docs/components/timeline/#default-timeline))
- [ ] Entität im CMS anlegen
