### ISSUE TITLE
Übersicht aller Tanzangebote

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#34]
# Übersicht aller Tanzangebote

**Als** Person mit Interesse am Tanzen
**möchte ich** einen Überblick über die Tanzangebote des Vereins erhalten
**um** einen passenden Kurs für mich zu finden.

## Akzeptanzkriterien

- [x] alle Angebote des Vereins werden übersichtlich dargestellt
  - [x] Turniertanz Standard
  - [x] Turniertanz Latein
  - [x] Kindertanzen
  - [x] Kinder / Junioren / Jugend Standard
  - [x] Kinder / Junioren / Jugend Latein
  - [x] Standardformation
  - [x] Lateinformation
  - [x] Freizeittanz
- [x] durch das Klicken auf das Angebot bzw. die CTA wird man auf die jeweilige Unterseite verlinkt
- [x] die Seite ist in folgende Sektionen gegliedert
  - [x] Turniertanz
    - [x] Standard
    - [x] Latein
  - [x] Formation
    - [x] Standard
    - [x] Latein
  - [x] Kinder & Jugend
    - [x] Allgemein
    - [x] Standard
    - [x] Latein
  - [x] Freizeit

## TODOs

- [x] Wireframe erstellen
- [x] Designprototyp erstellen
- [ ] passende Bilder finden
  - [ ] Turniertanz (Standard)
  - [ ] Turniertanz (Latein)
  - [ ] Formation (Standard)
  - [x] Formation (Latein)
  - [x] Kindertanzen (Allgemein)
  - [ ] Kinder / Jugend (Standard)
  - [ ] Kinder / Jugend (Latein)
  - [ ] Freizeittanzen
- [x] Texte zu den jeweiligen Sektionen bzw. Angeboten formulieren
- [x] einheitliche Hintergrundfarbe einstellen

---

### Turniertanz

Entdecke das besondere Feeling des Turniertanzes und erlebe unvergessliche Momente auf der Tanzfläche. Unser qualifiziertes Trainerteam begleitet dich auf dem Weg zum Turniertänzer und unterstützt dich bei deinen Wettkämpfen.

### Formationstanzen

Formationstanzen ist nicht nur eine besondere Form des Tanzens, sondern auch eine tolle Möglichkeit, neue Leute kennenzulernen und gemeinsam etwas zu erschaffen. Bei uns findest du die perfekte Mischung aus anspruchsvoller Choreografie und gemeinsamem Teamspirit.

### Kinder & Jugend

Spielerisch tanzen lernen – bei uns ist das möglich! Wir bieten Kindern und Jugendlichen unterschiedlichen Alters mit verschiedenen Tanzrichtungen ein Programm, das Spaß und Freude am Tanzen vermittelt.

### Freizeittanzen

In unseren Freizeittanz-Kursen ist jeder willkommen, der Lust auf Bewegung und Musik hat – unabhängig von Alter, Geschlecht oder Vorerfahrung. Entdecke deine Leidenschaft für verschiedene Tanzstile und lerne neue Menschen kennen.

**Comment by VitaliaSvirskaja** [comment]
Design muss vor weiterem Programmieren geklärt werden

**Comment by DanielMerkl** [comment]
Fehlende Bilder in folgendem Ticket dokumentiert #39
