### ISSUE TITLE
News

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#37]
# News

**Als** Verein
**möchte ich** Neuigkeiten auf der Webseite veröffentlichen
**um** Mitglieder und andere interessierte Personen über das laufende Vereinsgeschehen zu informieren. 

## Akzeptanzkriterien

- [x] News können von den Content-Administratoren im CMS gepflegt werden
- [x] News haben folgenden Inhalt:
  - [x] Bild
  - [x] Überschrift (normaler Text)
  - [x] Content (WYSIWYG)
  - [x] Chronologische Position (Datum & Uhrzeit; dient zur chronologischen Sortierung der News; unabhängig von Veröffentlichungs- bzw. Änderungsdatum)
  - [x] Vorschau-Text
- [x] Homepage
  - [x] es werden nur die neuesten 3 News angezeigt
  - [x] die Preview-Cards beinhalten:
    - [x] Bild
    - [x] Überschrift (maximal 2 Zeilen angezeigt)
    - [x] chronologisches Datum
- [x] Seite mit Liste aller News
  - [x] es werden nur die neuesten 6 News angezeigt
  - [x] Es gibt einen Button zum Laden weiterer News (keine SSG)
  - [x] folgende Inhalte werden bei den News angezeigt
    - [x] Bild
    - [x] Titel
    - [x] Vorschau-Text
    - [x] chronologisches Datum
- [x] Seite für Darstellung einzelne News stellt folgende Inhalte dar
  - [x] Titel
  - [x] Content
  - [x] chronologisches Datum
  - [x] Button um zur Übersicht zurückzukehren

## TODOs

- [x] Sektion auf Homepage mit den 3 neuesten News implementieren
- [x] Seite mit Liste aller News implementieren
- [x] Seite zur Darstellung einzelner News implementieren
- [x] Klären: wie geht man damit um, wenn kein Bild vorhanden ist, aber trotzdem ein Beitrag veröffentlicht werden soll

**Comment by VitaliaSvirskaja** [comment]
**Vorschlag für Umgang mit fehlenden Bildern:**
Im CMS sind generische Bilder vorhanden (z.B. Karikatur mit Siegertreppchen; kann eventuell von MidJourney generiert werden)

**Comment by VitaliaSvirskaja** [comment]
Lösung für News ohne vorhandene Bilder: Default Bilder aus dem Bilder Pool von Hermann (.z.Bsp. Bilder von den Händen der Tanzpaare - siehe "Viel Glück" Insta Posts)
