### ISSUE TITLE
Veranstaltungen

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#38]
# Veranstaltungen

**Als** Verein
**möchte ich** bevorstehende Veranstaltungen auf der Webseite veröffentlichen
**um** Mitglieder und andere interessierte Personen zu informieren.

## Akzeptanzkriterien

- [x] Veranstaltungen können von Content-Administratoren im CMS gepflegt werden
- [x] Veranstaltungen haben folgenden Inhalt:
  - [x] Titel
  - [x] Start-Datum
  - [x] Ende-Datum
  - [x] Content (WYSIWYG)
  - [x] Vorschau-Text
- [x] in der Übersicht werden nur Veranstaltungen in der Zukunft angezeigt

## TODOs

- [x] Designinspiration bzw. Komponenten suchen (Timeline?)
- [x] Felder für das CMS definieren
  - [x] Titel
  - [x] Beschreibung
  - [x] Vorschautext
  - [x] Start (Datum)
  - [x] Ende (Datum; optional)
  - [x] Veranstaltungsort (1:n)
  - [ ] TODO: weitere Felder definieren
- [x] Collection Type für Veranstaltungsorte anlegen
  - [x] Name (z.B. Berufsbildungszentrum)
  - [x] Straße
  - [x] Hausnummer
  - [x] Postleitzahl
  - [x] Stadt
- [x] Seite mit Auflistung aller bevorstehenden Veranstaltungen implementieren
- [x] Seite für Darstellung einer einzelnen Veranstaltung implementieren
- [x] Strapi auf Version `4.12.5` upgraden, sobald verfügbar (siehe https://github.com/strapi/strapi/pull/17599)

## Designinspirationen
Grundidee: Auflistung aller bevorstehender Veranstaltungen. [Die erste Veranstaltung wird groß mit mehr Informationen](https://dribbble.com/shots/20434407-Sport-Sharing-Apps-Exploration) angezeigt, die weiteren Veranstaltungen werden darunter aufgelistet.

### Auflistung
- [Monat und Datum](https://dribbble.com/shots/13327375-Event-Dashboard-List/attachments/4930069?mode=media)
-

**Comment by VitaliaSvirskaja** [comment]
Separater Termin mit Content Administratoren für die Definition der CMS Felder notwendig

**Comment by DanielMerkl** [comment]
### Meeting 05.08.

Zunächst 80% Lösung mit Collection Types abbilden.
Danach Single Types für wiederkehrende (besondere) Veranstaltungen (z.B. Formationswochenende, Mittelfränkisches, FDF etc.) als Basis für individuelle Veranstaltungs-Seiten.
