### ISSUE TITLE
Einzelne Angebotsseiten

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#44]
# Angebotsseite

**Als** Tanzinteressierter
**möchte ich** Informationen über ein Angebot einholen können 
**um** entscheiden zu können, ob mir das Angebot zusagt.

## Akzeptanzkriterien

- [x] das Angebot wird in einem kurzen Absatz erklärt
- [ ] ~~das Angebot wird durch ein passendes Bild veranschaulicht~~
- [x] die Uhrzeiten für **alle** Angebote werden in einem Kalender (Wochenansicht) dargestellt
- [ ] ~~der Kalendereintrag des aktuell angezeigten Angebots wird visuell hervorgehoben~~
- [x] für das aktuelle Angebot werden die jeweiligen Trainer mit folgenden Infos dargestellt:
  - [x] Bild
  - [x] Name
  - [x] Position (z.B. Cheftrainer, Gasttrainer)
  - [x] Trainerlizenz
  - [x] weitere Qualifikationen
- [x] FAQ werden am Ende der Seite angezeigt und sind können auf das jeweilige Angebot zugeschnitten werden
- [x] Unter den FAQs gibt es eine Sektion "Weitere Fragen?" mit Verlinkung auf Kontaktformular
- [x] es wird eine Information sichtbar dargestellt, dass in den Ferien keine Gruppenstunden stattfinden

## TODOs

- [x] Sollen und dürfen externe bzw. Gast-Trainer in der Übersicht-Sektion der Trainer des jeweiligen Angebots aufgelistet werden?
- [x] Komponente für Kalendervisualisierung suchen
- [x] Collection Type für alle Trainings anlegen
  - [x] Wochentag
  - [x] Start (Uhrzeit)
  - [x] Ende (Uhrzeit) 
  - [x] Titel
  - [x] Trainer (n:m)
  - [x] Saal
- [x] Collection Type für Angebote anlegen
  - [x] Titel
  - [x] Beschreibung (Richtext)
  - [x] Trainings (1:n Relation)
  - [x] Trainer (n:m Relation)
  - [x] FAQs (n:m Relation)
- [x] FAQ Schema im CMS anlegen
  - [x] Frage
  - [x] Antwort (Richtext)

---
Bugs
- [x] 18:0 Uhr
- [x] Lange Überschriften in Trainingseinheiten

**Comment by DanielMerkl** [comment]
### Ergebnis des Meetings vom 17.06.
Gast-Trainer sollen nicht aufgelistet werden
