### ISSUE TITLE
Passende Schriftart finden und umsetzen

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#53]
- Aktuell wird Manrope verwendet

### ToDos

- [x] Vorschläge für andere Schriftarten müssen beim AK Design eingekippt werden
- [x] Vorschläge für Schriftarten sollten aus Google Fonts stammen 
- [x] WiFi-Consent Page entsprechend anpassen
