### ISSUE TITLE
Gesonderte Angebotsseiten für Formationen erstellen

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#54]
### TODOs

- [x] Klären, was auf der Seite enthalten sein soll (Wer ist hierfür Ansprechpartner?)
- [x] Designprototyp für die darzustellenden Informationen erstellen
- [x] Single Types in Strapi CMS anlegen
- [x] Seiten implementieren
- [x] Beschreibung der Choreo

**Comment by VitaliaSvirskaja** [comment]
ASP: Jelena Celic und Michael Ortlieb

**Comment by DanielMerkl** [comment]
in Klärung

**Comment by DanielMerkl** [comment]
### Inspirationen
https://www.fcn.de/profis/team/spieler/
https://fcbayern.com/de/teams/profis
