### ISSUE TITLE
Kontaktformular Komponente erstellen

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#9]
# Kontaktformular Komponente

## ToDo
- [x] klären, ob das Kontaktformular aktiv genutzt wird
- [ ] klären, an welchen Verteiler die Kontaktanfrage rausgeschickt wird

## Inhalt der Komponente

- [x] Inputfelder mit Infos zur Person (Name, E-Mail, Telefonnummer)
- [x] Textfeld für die Nachricht
- [x] Zustimmung zur Verarbeitung. der Daten (Checkbox für Akzeptanz der Datenschutzerklärung)

## Akzeptanz Kriterien

- [x] Ablehnung der Kontaktanfrage bei nicht akzeptierter Datenschutzerklärung
- [x] Ablehnung der Kontaktanfrage bei freigelassenen Pflichtfeldern
- [x] Formvalidierung mit Error Nachrichten
- [x] responsive Design
- [ ] dark mode
- [ ] Tests
